### ISSUE TITLE
Not able to go beyond 60Hz and HDMI/DP audio not working, only audio jack audio is working.

### ISSUE THREAD

**Issue by adesheddie** [Dr-Dreams/ASROCK-B450M-PRO4-HACKINTOSH#1]
I am having RX 5700XT GPU and Ryzen 3 3200G CPU.

Everything else works fine, just these two issues I am not able to resolve, can you please confirm they are working at your end ?

**Comment by Dr-Dreams** [comment]
use Hdmi 2.0

**Comment by Dr-Dreams** [comment]
Did it work or not ?
Please let me know otherwise I will close this issue.

**Comment by adesheddie** [comment]
Actually I am using DP to HDMI Cable, maybe that’s the reason it’s not going beyond 60hz.

however, I am facing another major issue, my SSD write speed in BlackMagic goes down to 30MB/s, starting from 500MB/s, due to this issue, my MacOS is really laggy, 
Not able to use even just chrome.
Adobe premiere just hangs due to poor write speed.

How much write speed are you getting? And is it constant?

**Comment by Dr-Dreams** [comment]
Can you share your EFI files?
